[package]
name = "smart_socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "smart_socket"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.30"
