[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
name = "web"
path = "src/lib.rs"

[dependencies]
actix-web = "3.3.3"
serde = "1.0.136"
serde_json = "1.0.79"
smart-house = { path = "../smart-house", features = ["no-tokio"], default-features = false }
